### ISSUE TITLE
Entity Hitbox Problem

### ISSUE THREAD

**Issue by HalfSnowCN** [RayzsYT/ControlPlayer#3]
When I was using the ControlPlayer plugin, the server was shut down by another administrator. On the next launch, I noticed that my backpack was still in the controlled player group and my body was invisible. I have deleted my backpack data and everything has returned to normal. After a while, I realized that I couldn't push the entity, even if I removed the ControlPlayer plugin. Can you solve this problem, please!!!(I can be squeezed by entity, but I can't push it)

**Comment by HalfSnowCN** [comment]
hello?

**Comment by RayzsYT** [comment]
Can you send me a video how this issue looks exactly on your perspective. Because I'm not sure how to reproduce this by myself.

**Comment by HalfSnowCN** [comment]
[video.zip](https://github.com/RayzsYT/ControlPlayer/files/12207188/video.zip)

**Comment by HalfSnowCN** [comment]
I am very certain that this plugin is causing this problem

**Comment by RayzsYT** [comment]
What server version is ur server running on?

**Comment by HalfSnowCN** [comment]
1.16.5-AirplanePurpur You can find it on github

**Comment by RayzsYT** [comment]
Never heard of this and I couldn't even find it.
Can you please send me a direct link to this fork?

**Comment by RayzsYT** [comment]
> 1.16.5-AirplanePurpur You can find it on github

Hm?

**Comment by HalfSnowCN** [comment]
https://github.com/Technove/Airplane

**Comment by HalfSnowCN** [comment]
now, other controlled players on my server have also experienced similar issues. I shoot him with an arrow, he won't be hit, the arrow will go straight through his body.

**Comment by HalfSnowCN** [comment]
are you planning to fix this bug??

**Comment by RayzsYT** [comment]
Should be fixed now. 
If it still bugs, just type /cpf to fix the player who has no collision, or just yourself.
Or just reopen this issue

https://www.spigotmc.org/resources/102987/download?version=509521
